# Generated by Django 3.0.4 on 2020-03-30 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_type', models.CharField(max_length=50)),
                ('company_state', models.CharField(max_length=50)),
                ('company_city', models.CharField(max_length=20)),
                ('company_add', models.CharField(max_length=70)),
                ('company_pincode', models.CharField(max_length=10)),
                ('company_mobile_no', models.CharField(max_length=11)),
                ('company_email_id', models.EmailField(max_length=254)),
                ('company_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='pwd',
            field=models.CharField(max_length=12),
        ),
        migrations.CreateModel(
            name='job_provider',
            fields=[
                ('job_provider_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('job_provider_fname', models.CharField(max_length=50)),
                ('job_provider_mname', models.CharField(max_length=50)),
                ('job_provider_lname', models.CharField(max_length=50)),
                ('job_provider_gender', models.CharField(max_length=20)),
                ('job_provider_uid_type', models.CharField(max_length=50)),
                ('job_provider_uid_number', models.CharField(max_length=20)),
                ('job_provider_u_name', models.CharField(max_length=50)),
                ('job_provider_pwd', models.CharField(max_length=12)),
                ('company_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='MyApp.company', unique=True)),
            ],
        ),
    ]
