# Generated by Django 3.0.4 on 2020-03-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20200331_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_provider',
            name='job_provider_position',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
