# Generated by Django 3.0.4 on 2020-03-31 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_job_provider_job_provider_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_provider',
            old_name='company_id',
            new_name='job_provider_company_id',
        ),
    ]
