# Generated by Django 3.0.4 on 2020-03-31 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20200331_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_type', models.CharField(max_length=50)),
                ('u_name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='job_provider',
            name='job_provider_company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='MyApp.company'),
        ),
    ]
