# Generated by Django 3.0.4 on 2020-04-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_auto_20200401_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='u_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
