# Generated by Django 3.0.4 on 2020-04-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_auto_20200404_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_provider',
            name='jp_ans_security_question',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='job_provider',
            name='jp_security_question',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='js_ans_security_question',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='js_security_question',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
