# Generated by Django 3.0.4 on 2020-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_auto_20200407_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_provider',
            name='job_provider_pwd',
        ),
        migrations.RemoveField(
            model_name='job_provider',
            name='job_provider_u_name',
        ),
        migrations.AddField(
            model_name='job_provider',
            name='pwd',
            field=models.CharField(default='DEFAULT VALUE', max_length=12),
        ),
        migrations.AddField(
            model_name='job_provider',
            name='u_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50, unique=True),
        ),
    ]
