# Generated by Django 3.0.4 on 2020-04-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_auto_20200408_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='', upload_to='static/Company_Logo'),
        ),
    ]
