# Generated by Django 3.0.4 on 2020-04-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_company_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='', null=True, upload_to='static/Company_Logo'),
        ),
    ]
