# Generated by Django 3.0.4 on 2020-04-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_auto_20200417_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='static/Company_Logo/default_logo.png', null=True, upload_to='static/Company_Logo'),
        ),
    ]
