# Generated by Django 3.0.4 on 2020-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_auto_20200417_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_details',
            fields=[
                ('jd_company_id', models.CharField(max_length=11)),
                ('jd_company_name', models.CharField(max_length=50)),
                ('jd_job_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('jd_position', models.CharField(max_length=20)),
                ('jd_location', models.CharField(max_length=50)),
                ('jd_skills_required', models.CharField(max_length=50)),
                ('jd_category', models.CharField(max_length=50)),
                ('jd_salary', models.FloatField(max_length=10)),
                ('jd_vacancy', models.IntegerField()),
                ('jd_experience', models.IntegerField()),
                ('jd_description', models.CharField(max_length=300)),
                ],
        ),
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(default='static/Company_Logo/symbol.png', upload_to='static/Company_Logo'),
        ),
    ]
