# Generated by Django 3.0.4 on 2020-05-06 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_auto_20200506_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='jd_apply_by',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='job_details',
            name='jd_duration',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job_details',
            name='jd_posted_on',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='job_details',
            name='jd_start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
