# Generated by Django 3.0.4 on 2020-05-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_auto_20200506_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_details',
            name='jd_perks',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='jd_salary',
            field=models.CharField(max_length=10),
        ),
    ]
