# Generated by Django 3.0.4 on 2020-05-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_auto_20200512_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='js_profile_pic',
            field=models.ImageField(default='static/User_profile/profile.png', upload_to='static/User_profile'),
        ),
    ]
