# Generated by Django 3.0.4 on 2020-05-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_job_seeker_js_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewApplicants',
            fields=[
                ('va_job_id', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='MyApp.job_details')),
                ('va_u_name', models.CharField(max_length=50)),
                ('va_company_name', models.CharField(max_length=50)),
            ],
        ),
    ]
