# Generated by Django 3.0.4 on 2020-05-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0024_viewapplicants_va_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewapplicants',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viewapplicants',
            name='va_job_id',
            field=models.CharField(default='Default', max_length=11),
        ),
    ]
