# Generated by Django 3.0.4 on 2020-05-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0026_viewapplicants_va_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_provider',
            name='job_provider_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='MyApp.company'),
        ),
    ]
