# Generated by Django 3.0.4 on 2020-05-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0027_auto_20200513_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_provider',
            name='u_name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
