# Generated by Django 3.0.4 on 2020-05-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0028_auto_20200513_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_provider',
            name='job_provider_company',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
