# Generated by Django 3.0.4 on 2020-05-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0029_auto_20200513_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_provider',
            old_name='job_provider_company',
            new_name='job_provider_company_id',
        ),
    ]
