# Generated by Django 2.2 on 2020-05-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0030_auto_20200513_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='viewApplicants_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('va_job_id', models.CharField(default='Default', max_length=11)),
                ('va_u_name', models.CharField(max_length=50)),
                ('va_company_name', models.CharField(max_length=50)),
                ('va_resume', models.FileField(null=True, upload_to='static/Resume')),
                ('va_status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
