from django.urls import path
from . import views

urlpatterns = [
path('',views.home,name = 'home'),
path('login',views.login,name = 'login'),
path('JS',views.JS,name = 'JobSeeker'),
path('JP',views.JP,name = 'JobProvider'),
path('AS',views.AS,name = 'AboutUs'),
path('CS',views.CS,name = 'ContactUs'),
path('uname',views.uname,name = 'username'),
path('resetpwd',views.resetpwd,name = 'resetpasswd'),
path('SavePass',views.SavePass,name = 'SavePass'),
path('forgotpwd',views.forgotpwd,name = 'forgotpasswd'),
path('updateJS',views.updateJS,name = 'updateJS'),
path('UPJS',views.UPJS,name = 'UPJS'),
path('UPJP',views.UPJP,name = 'UPJP'),
path('updateJP',views.updateJP,name = 'updateJP'),
path('JD',views.JD,name = 'jobdetails'),
path('HJD',views.HJD,name = 'Updatejd'),
path('UPJD',views.UPJD,name = 'UPJD'),
path('HJS_',views.HJS_,name = 'HJS_'),
path('HJP',views.HJP,name = 'homejp'),
path('VAC',views.VAC,name = 'viewapp'),
path('AddJob',views.AddJob,name='AddJob'),
path('FilterJob',views.FilterJob,name='FilterJob'),
path('CJD',views.CJD,name='CompJobdet'),
path('Jstatus',views.Jstatus,name='Jstatus'),
path('UpResume',views.UpResume,name='UpResume'),
path('Accept',views.Accept,name='Accept'),
path('Jstatus',views.Jstatus,name='Jstatus'),
path('EditPP',views.EditPP,name='EditPP'),
path('EditJS',views.EditJS,name='EditJS'),
]